# Change these first
owner: CoCoGoat-Network # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: Dashboard
    url: https://app.netbird.uno
  - name: Management Service
    url: https://app.netbird.uno/api
  - name: STUN Server
    url: http://stun.netbird.uno
    port: 3478
    check: "tcp-ping"
  - name: Relay Service - Guangzhou
    url: http://relay.netbird.uno
    port: 10000
    check: "tcp-ping"
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.netbird.uno
  # baseUrl: /your-repo-name
  logoUrl: https://netbird.uno/logo.png
  name: NetBird Status
  introTitle: "此页面显示 NetBird 各项服务的运行状态 | This page shows the status of various NetBird services"
  introMessage: 欢迎来到在线SLA竞技大赛!!!
  navbar:
    - title: Status
      href: /
    - title: Dashboard
      href: https://app.netbird.uno
    - title: Home
      href: https://netbird.uno


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
